stages:
- name: test
  if: branch != master AND type = push AND tag is blank
- name: npm
  if: branch = master AND type = push AND tag is blank
- name: github
  if: branch = master AND type = push AND tag is blank
jobs:
  include:
  - stage: test
    language: node_js
    node_js:
    - lts/*
    dist: xenial
    install:
    - npm i
    script:
      - npm run build
      - npm test
      - npm run lint
  - stage: npm
    language: node_js
    node_js:
    - lts/*
    dist: xenial
    install:
    - npm i
    script:
    - npm run build
    deploy:
      provider: npm
      email: npm@parasrah.com
      api_key:
        secure: ak2ehelAE8HNgeECRuQdW5D2BlKXs3PBrNhZUjgAFmazQTjbtbOrbcfohcaQEUKUSOGlBTk+tA6ydnUoO7GdEVWLA8BHsHDWb+z6KnxXXE/fTDxTIx/Irop8J8Niue8c5PTf+29uYukHb9Ula0Kc3g69vsPgRA0WfXOizmQ4t4JxOTAxOfdURlQm5HdH2NnjB0wGFx62ufmflEVMrrbUy2/K0jhUITZTHusT0s3tvF8GrztWvd9ieluhG35M317Npfcq6X7f+fSt7Q4e7EkQqI0COgJCTENeNppysBqSHfheJ/1O5OrcosGI88n4jcZWuajjcBuPVYciB+8hMItUEr6TFVtyrIS/ocbcp2dwMucI+I/tKmM0PV914nLb8q2Omz0nb59C4z8VKe5dFMX/GH/U7rf+35l+br9NUnUdPJG+2qf/tWeiSwu5IZF4vE1PmULxDdG/CBIEB69EVXzga+qbh/63Z9gAs7VmtMxTBI/cq37iJW7SUF1pOk2aEJBy5v40sr+hPD4xqpdn1xN6EirnA/nUqLbM9PhVoQypep9LckLmjYr8lBZDx4rE8eoGUIPRzxw8L8aGGH0fY0G/pI9ln4ysCcG8r3+7ZO8I7r7vpqI75YC40OrICc7Il02bNk6SnCW0/hdRxFDpn6fzKxxobJaQtE70fQMT22e3CaI=
      skip_cleanup: true
  - stage: github
    language: node_js
    node_js:
    - lts/*
    dist: xenial
    install: npm i
    script: npm run build
    before_deploy:
    - export TRAVIS_TAG=$(npm run version | tail -n1)
    - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      file_glob: true
      file: dist/*
      api_key:
        secure: qy6DURjgjrw+KUcTAave2OGPLLjsnrGqZ4TQzbTlC/M2FuqdLWqClf9wgnkzVYpJn9iPFRWmrglI1DgNGUwppyEHhkJI5wtNvHzprFVQAaWUlSvZ99okVwfaW4yOYBW9WO11UC54boacgUqK+cO2cw3PBYsHPHQ40OPK2faeZc1MVfZHmkPVf/3lpqIVKbOzP5LeiP7xVOx51wYweIeG6iJAWKDpiZH0ZCKaYHAW9ZZKwz3zXAFNnp2R81abHca3BdcdcVUArB/B+jbg4AFOej+AEC0VbkzetWexCjZL3lGnrxpJ4+tJBjy3zuqSRVNs2m92sbAY1zT5eV/GOLkbQoOjRTgQIeFNUe2AdX7xWuHlWU9UQGSG528wjwMWlmblR44A2Uem6OME+Q+gbCBuETIyUDsRJsNaIthoGMyaU0Y4M0N0tqEEeNjV1rKYVz6/pGVmV4hHsbw9eZ9hfweeeHcJZbJFxOuDaXmBSvRyjOTOVu3+0tu6DrXYfPVYbKenYVl+J2csWJCgc9l1piNSMSwEsGvUH6oRVRYjAtXD9o+n00hbJMurNpzRev91onWFOuq7cHkE8FM4yO38S4u1BpZ3TX+1Wmt28vJFuUzt2yvrGD3HEjfJR+MEqo+5V67UVPimYjThiURSa4gE3fbb3BMmbYXQqKM6dYQhYyyhRyg=
      skip_cleanup: true
